SR3.2/Models/Device/AbstactDevice.cs
namespace SR3._2.Models.Device
{
    public abstract class AbstractDevice
    {
        public int Id { get; set; }
        public bool state;
        public AbstractDevice() { }
        public void OnOff()
        {
            state = !state;
        }
        public bool State
        {
            get
            {
                return state;
            }
            set
            {
                state = value;
            }
        }
    }

}

SR3.2/Models/Device/Boiler.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("Fire")]
    public class Boiler : Temperature
    {
        public Boiler() { }
        public Boiler(bool state,  int Temp)
            : base(Temp)
        {        }

        public override string ToString()
        {

            return "Котел - состояние: ";
        }
    }
}

SR3.2/Models/Device/Conditioner.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("Cooler")]
    public class Conditioner : Temperature
    {
        public Conditioner() { }
        public Conditioner(bool state,  int Temp)
            : base( Temp)
        {        }

        public override string ToString()
        {
            return "Кондиционер : состояние: ";
        }
    }
}

SR3.2/Models/Device/Fridge.cs
using SR3._2.Models.Interfaces;

using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("Freee")]
    public class Fridge : Temperature, IOpenClose
    {
        private bool openclose;
    
        public Fridge() { }
        public Fridge(bool state, int Temp, bool openclose)
            : base( Temp)
        {
            this.openclose = openclose;
        }

        public bool OpenClose
        {
            get { return openclose; }
            set { openclose = value; }

        }
        public void OpCl()
        {
            openclose = !openclose;
        }

        public override string ToString()
        {
            return "Холодильник - состояние: ";
        }
    }
}

SR3.2/Models/Device/MC.cs
using SR3._2.Models.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("MC")]
    public class MC : AbstractDevice, IChangeChennel, IVolume
    {
        public MC() { } 
        public MC(bool state, int chennel, int volume)
        {
            this.volume = volume;
            this.chennel = chennel;
        }

        public int chennel;
        public int volume;

        public int Chennel
        {
            get { return chennel; }
            set { chennel = value; }
        }

        public int Volume
        {
            get { return volume; }
            set { volume = value; }
        }

        public void NextChennel()
        {
            if (Chennel < 200)
            { Chennel++; }
        }

        public void PreviusChennel()
        {
            if (Chennel > 0)
            { Chennel--; }
        }

        public void DecreaseVolume()
        {
            if (Volume > 0)
            { Volume--; }
        }

        public void IncreaseVolume()
        {
            if (Volume < 100) { Volume++; }
        }

        public override string ToString()
        {
            return "Музыкальный центр - состояние: ";
        }
    }
}

SR3.2/Models/Device/TV.cs
using SR3._2.Models.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("TV")]
    public class TV : AbstractDevice, IVolume, IChangeChennel
    {
        public int chennel;
        public int volume;
        public TV() { }
        public TV(bool state, int chennel, int volume)
        {
            this.volume = volume;
            this.chennel = chennel;
        }

        public int Chennel
        {
            get { return chennel; }
            set { chennel = value; }
        }

        public int Volume
        {
            get { return volume; }
            set { volume = value; }
        }

        public void NextChennel()
        {
            if (Chennel < 200)
            { Chennel++; }
        }

        public void PreviusChennel()
        {
            if (Chennel > 0)
            { Chennel--; }
        }

        public void DecreaseVolume()
        {
            if (Volume > 0)
            { Volume--; }
        }

        public void IncreaseVolume()
        {
            if (Volume < 100) { Volume++; }
        }

        public override string ToString()
        {

            return "Телевизор - состояние: ";
        }
    }
}

SR3.2/Models/Device/Temperature.cs
using SR3._2.Models.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace SR3._2.Models.Device
{
    [Table("Temp")]
    public abstract class Temperature : AbstractDevice, IRegulatorTemp
    {
        //public int Max
        //{ get; set; }
        //public int Min
        //{ get; set; }
        //public int temp;
        public Temperature() { }
        public Temperature( int Temp )
        {         }
        public int Temp
        { get; set; }
        public void DecreaseTemp()
        {
            Temp--;
        }

        public void IncreaseTemp()
        {
            Temp++;
        }
 
    }
}

SR3.2/Controllers/DeviceController.cs
using SamRab3_2.Models.Contex;
using SR3._2.Models.Device;
using SR3._2.Models.Interfaces;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SR3._2.Controllers
{
    public class DeviceController : Controller
    {
        private SmartHomeContex bb = new SmartHomeContex();
        public ActionResult Index()
        {
            IList<AbstractDevice> list = new List<AbstractDevice>();

            foreach (AbstractDevice item in bb.Devices.ToList())
            {
                list.Add(item);
            }


            SelectListItem[] appList = new SelectListItem[5];
            appList[0] = new SelectListItem { Text = "Жароед", Value = "boiler" };
            appList[1] = new SelectListItem { Text = "Студилко", Value = "cond" };
            appList[2] = new SelectListItem { Text = "Едасхрон", Value = "fridge" };
            appList[3] = new SelectListItem { Text = "Контробасс", Value = "musik" };
            appList[4] = new SelectListItem { Text = "Телик", Value = "tvset" };
            ViewBag.AppList = appList;

            return View(list);
        }

        public ActionResult Add(string deviceType)
        {
            AbstractDevice newDevice;
            switch (deviceType)
            {
                case "tvset":
                    newDevice = new TV(false, 100, 50);
                    break;
                case "musik":
                    newDevice = new MC(false, 100, 50);
                    break;
                case "boiler":
                    newDevice = new Boiler(false, 23);
                    break;
                case "cond":
                    newDevice = new Conditioner(false, 20);
                    break;
                default:
                    newDevice = new Fridge(false, -5, false);
                    break;
            }

            bb.Devices.Add(newDevice);
            bb.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult OnOff(int id)
        {
            AbstractDevice z = bb.Devices.Find(id);
            if (z != null)
            {
                z.OnOff();
                bb.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null) { return HttpNotFound(); }
            AbstractDevice b = bb.Devices.Find(id);
            if (b != null)
            {
                bb.Devices.Remove(b);
                bb.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult OpenClose(int id)
        {
            Fridge opcl = bb.Fredges.Find(id);
            if (opcl != null)
            {
                opcl.OpCl();
                bb.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult TempIncrease(int id)
        {
            Temperature newtemp = bb.Temperatures.Find(id);
            if (newtemp != null)
            {
                switch (id)
                {
                    case 1:
                        newtemp.IncreaseTemp();
                        break;
                    case 2:
                        newtemp.IncreaseTemp();
                        break;
                    default:
                        newtemp.IncreaseTemp();
                        break;
                }
                bb.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult TempDecrease(int id)
        {
            Temperature newtemp = bb.Temperatures.Find(id);
            if (newtemp != null)
            {
                switch (id)
                {
                    case 1:
                        newtemp.DecreaseTemp();
                        break;
                    case 2:
                        newtemp.DecreaseTemp();
                        break;
                    default:
                        newtemp.DecreaseTemp();
                        break;
                }
                bb.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult VolumeIncr(int id)
        {
            if (id == 4)
            {
                IVolume newvol = bb.MCs.Find(id);
                newvol.IncreaseVolume();
            }
            if (id == 5)
            {
                IVolume newvol2 = bb.TVs.Find(id);
                newvol2.IncreaseVolume();
            }
            bb.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VolumeDecr(int id)
        {
            if (id == 4)
            {
                IVolume newvol = bb.MCs.Find(id);
                newvol.DecreaseVolume();
            }
            if (id == 5)
            {
                IVolume newvol2 = bb.TVs.Find(id);
                newvol2.DecreaseVolume();
            }
            bb.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult NextChenell(int id)
        {
            if (id == 4)
            {
                IChangeChennel newvol = bb.MCs.Find(id);
                newvol.NextChennel();
            }
            if (id == 5)
            {
                IChangeChennel newvol2 = bb.TVs.Find(id);
                newvol2.NextChennel();
            }
            bb.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PrevChenell(int id)
        {
            if (id == 4)
            {
                IChangeChennel newvol = bb.MCs.Find(id);
                newvol.PreviusChennel();
            }
            if (id == 5)
            {
                IChangeChennel newvol2 = bb.TVs.Find(id);
                newvol2.PreviusChennel();
            }
            bb.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

SR3.2/Views/Device/Index.cshtml
@using SR3._2.Models.Device
@using SR3._2.Models.Interfaces
@model  IList<AbstractDevice>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Фигуры</title>
    <style>
        .figure-div {
            border: 1px solid black;
            float: left;
            margin: 3px;
            padding: 3px;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Add", "Device"))
        {
            @Html.DropDownList("deviceType", (IEnumerable<SelectListItem>)ViewBag.applist)
            <input type="submit" value="Добавить">
        }

        @foreach (var item in Model)
        {
            <div class="figure-div">
                Устройство: @item<br />
                <div>
                    <a href="/Device/OnOff/@item.Id">Вклюв/выклюв</a><br>
                    Вклю: @(item.State)
                </div>
                @if (item is IVolume)
                {
                    using (Html.BeginForm("Volume" + item.Id, "Device"))
                    {
                        <div>
                            Громкость крика: @(((IVolume)item).Volume)
                            <a href="/Device/VolumeIncr/@item.Id" id="getvol">Добавить крика</a>
                            <a href="/Device/VolumeDecr/@item.Id" id="gettv">Убавить крика</a>
                            <div id="result"></div>
                        </div>
                    }
                }
                @if (item is IRegulatorTemp)
                {
                    using (Html.BeginForm("Temp" + item.Id, "Device"))
                    {
                        <div>
                            Температура: @(((IRegulatorTemp)item).Temp)
                            <a href="/Device/TempIncrease/@item.Id">Испепелить</a>
                            <a href="/Device/TempDecrease/@item.Id">Отморозить</a>
                        </div>
                    }
                }

                @if (item is IChangeChennel)
                {
                    using (Html.BeginForm("Chennel" + item.Id, "Device"))
                    {
                        <div>
                            Канал ужасти: @(((IChangeChennel)item).Chennel)
                            <a href="/Device/NextChenell/@item.Id">Следующий кханурик</a>
                            <a href="/Device/PrevChenell/@item.Id">Предедущий кханурик</a>
                        </div>
                    }
                }
                @if (item is IOpenClose)
                {
                    using (Html.BeginForm("OpenClose" + item.Id, "Device"))
                    {
                        <div>
                            Дверца: @(((IOpenClose)item).OpenClose)
                            <a href="/Device/OpenClose/@item.Id">Открыть/Закрыть врата</a>
                        </div>
                    }
                }

                @using (Html.BeginForm("Delete" + item.Id, "Device"))
                {
                    <a href="/Device/Delete/@item.Id">Изничтожить</a>
                }
            </div>
            @*<button id="postObj">Post object</button>
                <input type="text" id="name" />
                <input type="text" id="age" />*@

            @*<script>
                $(function () {
                    $("#gettv").click(function () {
                        $.ajax({
                            url: "/api/values/tv",
                            type: "GET",

                            success: function (data) {
                                $("#result").html();
                            }
                        });
                    });*@

            //    $("#postObj").click(function () {
            //        var p = {
            //            Name: $("#name").val(),
            //            Age: $("#age").val()
            //        };
            //        $.ajax({
            //            url: "/api/values",
            //            type: "POST",
            //            data: JSON.stringify(p),
            //            contentType: "application/json;charset=utf-8",
            //            success: function (data) {
            //                $("#result").html(data);
            //            }
            //        });
            @*//    });
                        //});
                </script>*@
        }
</body>
</html>